import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Sidebar from "~/component/complex/Sidebar";
import Box from "~/component/simple/Box";
import Math from "~/component/math/Math";
import { api } from "~/utils/api";
import Phone from "~/component/phone/Phone";
import Header from "~/component/header/header";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Front End Practice</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#467af3] to-[#d9daee]">
        {/* <Box title="Boxes" text="lorum is cool" num={6}/>
        <Sidebar title="SideBar really Big and beautiful" text="it is a big beautiful side bar " */}
        {/* Phone={555555555}/> */}
       


        <div>
            <Header tab1="My Work" tab2="My Resume" tab3="Connect with me"/>
            <Sidebar title="Sidebar" text="wee" phone={22323}/>

          {/* <Phone phone={123456}  call="Call Dad's Work"/>
          <Phone phone={518798}  call="Call Dad Home"/> */}
 
      
        </div>

        <div>
          {/* <Math title_style="title_lg"num1={100} num2={50} math="subtract"/>
          <Math title_style="title_reg"num1={100} num2={50} math="subtract"/> */}
        {/* <Math num1={100} num2={50} math="multiply"/>
        <Math num1={100} num2={50} math="divide"/>
        <Math num1={100} num2={50} math="add"/> */}
        </div>
      </main>
    </>
  );
};

export default Home;
